# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 15:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20180125_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost_users_likes',
            name='users_like',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='articles_like',
            field=models.CharField(default=datetime.datetime(2018, 1, 28, 15, 20, 19, 249294, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 15, 20, 19, 249253, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='articlePost_Users_Likes',
        ),
    ]
