# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180128_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='articles_like',
            field=models.CharField(default=datetime.datetime(2018, 1, 28, 15, 22, 34, 533784, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 15, 22, 34, 533744, tzinfo=utc)),
        ),
    ]
