# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180131_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='articles_like',
            field=models.CharField(default=datetime.datetime(2018, 2, 5, 14, 1, 34, 125484, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 14, 1, 34, 125435, tzinfo=utc)),
        ),
    ]
