# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180205_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='articles_like',
            field=models.CharField(default=datetime.datetime(2018, 2, 9, 9, 55, 56, 8603, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 9, 55, 56, 8563, tzinfo=utc)),
        ),
    ]
