# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180210_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='articles_like',
            field=models.CharField(default=datetime.datetime(2018, 2, 10, 9, 7, 6, 454281, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 9, 7, 6, 454240, tzinfo=utc)),
        ),
    ]
